/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ArticleRouteImport } from './routes/article'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ArticleWritingRouteImport } from './routes/article_.writing'
import { Route as ArticleCategoryRouteImport } from './routes/article_.$category'
import { Route as ArchiveProjectTitleRouteImport } from './routes/archive_.$projectTitle'
import { Route as ArticleTagTagSlugRouteImport } from './routes/article_.tag_.$tagSlug'
import { Route as ArticleEditPostIdRouteImport } from './routes/article_.edit_.$postId'
import { Route as ArticleCategoryPostTitleRouteImport } from './routes/article_.$category_.$postTitle'

const ArticleRoute = ArticleRouteImport.update({
  id: '/article',
  path: '/article',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleWritingRoute = ArticleWritingRouteImport.update({
  id: '/article_/writing',
  path: '/article/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleCategoryRoute = ArticleCategoryRouteImport.update({
  id: '/article_/$category',
  path: '/article/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveProjectTitleRoute = ArchiveProjectTitleRouteImport.update({
  id: '/archive_/$projectTitle',
  path: '/archive/$projectTitle',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleTagTagSlugRoute = ArticleTagTagSlugRouteImport.update({
  id: '/article_/tag_/$tagSlug',
  path: '/article/tag/$tagSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleEditPostIdRoute = ArticleEditPostIdRouteImport.update({
  id: '/article_/edit_/$postId',
  path: '/article/edit/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleCategoryPostTitleRoute =
  ArticleCategoryPostTitleRouteImport.update({
    id: '/article_/$category_/$postTitle',
    path: '/article/$category/$postTitle',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/article': typeof ArticleRoute
  '/archive/$projectTitle': typeof ArchiveProjectTitleRoute
  '/article/$category': typeof ArticleCategoryRoute
  '/article/writing': typeof ArticleWritingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/article/$category/$postTitle': typeof ArticleCategoryPostTitleRoute
  '/article/edit/$postId': typeof ArticleEditPostIdRoute
  '/article/tag/$tagSlug': typeof ArticleTagTagSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/article': typeof ArticleRoute
  '/archive/$projectTitle': typeof ArchiveProjectTitleRoute
  '/article/$category': typeof ArticleCategoryRoute
  '/article/writing': typeof ArticleWritingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/article/$category/$postTitle': typeof ArticleCategoryPostTitleRoute
  '/article/edit/$postId': typeof ArticleEditPostIdRoute
  '/article/tag/$tagSlug': typeof ArticleTagTagSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/article': typeof ArticleRoute
  '/archive_/$projectTitle': typeof ArchiveProjectTitleRoute
  '/article_/$category': typeof ArticleCategoryRoute
  '/article_/writing': typeof ArticleWritingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/article_/$category_/$postTitle': typeof ArticleCategoryPostTitleRoute
  '/article_/edit_/$postId': typeof ArticleEditPostIdRoute
  '/article_/tag_/$tagSlug': typeof ArticleTagTagSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/archive'
    | '/article'
    | '/archive/$projectTitle'
    | '/article/$category'
    | '/article/writing'
    | '/auth/callback'
    | '/article/$category/$postTitle'
    | '/article/edit/$postId'
    | '/article/tag/$tagSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/archive'
    | '/article'
    | '/archive/$projectTitle'
    | '/article/$category'
    | '/article/writing'
    | '/auth/callback'
    | '/article/$category/$postTitle'
    | '/article/edit/$postId'
    | '/article/tag/$tagSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/archive'
    | '/article'
    | '/archive_/$projectTitle'
    | '/article_/$category'
    | '/article_/writing'
    | '/auth/callback'
    | '/article_/$category_/$postTitle'
    | '/article_/edit_/$postId'
    | '/article_/tag_/$tagSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchiveRoute: typeof ArchiveRoute
  ArticleRoute: typeof ArticleRoute
  ArchiveProjectTitleRoute: typeof ArchiveProjectTitleRoute
  ArticleCategoryRoute: typeof ArticleCategoryRoute
  ArticleWritingRoute: typeof ArticleWritingRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ArticleCategoryPostTitleRoute: typeof ArticleCategoryPostTitleRoute
  ArticleEditPostIdRoute: typeof ArticleEditPostIdRoute
  ArticleTagTagSlugRoute: typeof ArticleTagTagSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/article': {
      id: '/article'
      path: '/article'
      fullPath: '/article'
      preLoaderRoute: typeof ArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article_/writing': {
      id: '/article_/writing'
      path: '/article/writing'
      fullPath: '/article/writing'
      preLoaderRoute: typeof ArticleWritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article_/$category': {
      id: '/article_/$category'
      path: '/article/$category'
      fullPath: '/article/$category'
      preLoaderRoute: typeof ArticleCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive_/$projectTitle': {
      id: '/archive_/$projectTitle'
      path: '/archive/$projectTitle'
      fullPath: '/archive/$projectTitle'
      preLoaderRoute: typeof ArchiveProjectTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article_/tag_/$tagSlug': {
      id: '/article_/tag_/$tagSlug'
      path: '/article/tag/$tagSlug'
      fullPath: '/article/tag/$tagSlug'
      preLoaderRoute: typeof ArticleTagTagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article_/edit_/$postId': {
      id: '/article_/edit_/$postId'
      path: '/article/edit/$postId'
      fullPath: '/article/edit/$postId'
      preLoaderRoute: typeof ArticleEditPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article_/$category_/$postTitle': {
      id: '/article_/$category_/$postTitle'
      path: '/article/$category/$postTitle'
      fullPath: '/article/$category/$postTitle'
      preLoaderRoute: typeof ArticleCategoryPostTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchiveRoute: ArchiveRoute,
  ArticleRoute: ArticleRoute,
  ArchiveProjectTitleRoute: ArchiveProjectTitleRoute,
  ArticleCategoryRoute: ArticleCategoryRoute,
  ArticleWritingRoute: ArticleWritingRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ArticleCategoryPostTitleRoute: ArticleCategoryPostTitleRoute,
  ArticleEditPostIdRoute: ArticleEditPostIdRoute,
  ArticleTagTagSlugRoute: ArticleTagTagSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
