/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ArticleCategoryImport } from './routes/article_.$category'
import { Route as ArticleWritingImport } from './routes/article.writing'
import { Route as ArchiveProjectTitleImport } from './routes/archive_.$projectTitle'
import { Route as ArticleCategoryPostTitleImport } from './routes/article_.$category_.$postTitle'

// Create Virtual Routes

const ArticleLazyImport = createFileRoute('/article')()
const ArchiveLazyImport = createFileRoute('/archive')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ArticleLazyRoute = ArticleLazyImport.update({
  id: '/article',
  path: '/article',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/article.lazy').then((d) => d.Route))

const ArchiveLazyRoute = ArchiveLazyImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/archive.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ArticleCategoryRoute = ArticleCategoryImport.update({
  id: '/article_/$category',
  path: '/article/$category',
  getParentRoute: () => rootRoute,
} as any)

const ArticleWritingRoute = ArticleWritingImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => ArticleLazyRoute,
} as any)

const ArchiveProjectTitleRoute = ArchiveProjectTitleImport.update({
  id: '/archive_/$projectTitle',
  path: '/archive/$projectTitle',
  getParentRoute: () => rootRoute,
} as any)

const ArticleCategoryPostTitleRoute = ArticleCategoryPostTitleImport.update({
  id: '/article_/$category_/$postTitle',
  path: '/article/$category/$postTitle',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveLazyImport
      parentRoute: typeof rootRoute
    }
    '/article': {
      id: '/article'
      path: '/article'
      fullPath: '/article'
      preLoaderRoute: typeof ArticleLazyImport
      parentRoute: typeof rootRoute
    }
    '/archive_/$projectTitle': {
      id: '/archive_/$projectTitle'
      path: '/archive/$projectTitle'
      fullPath: '/archive/$projectTitle'
      preLoaderRoute: typeof ArchiveProjectTitleImport
      parentRoute: typeof rootRoute
    }
    '/article/writing': {
      id: '/article/writing'
      path: '/writing'
      fullPath: '/article/writing'
      preLoaderRoute: typeof ArticleWritingImport
      parentRoute: typeof ArticleLazyImport
    }
    '/article_/$category': {
      id: '/article_/$category'
      path: '/article/$category'
      fullPath: '/article/$category'
      preLoaderRoute: typeof ArticleCategoryImport
      parentRoute: typeof rootRoute
    }
    '/article_/$category_/$postTitle': {
      id: '/article_/$category_/$postTitle'
      path: '/article/$category/$postTitle'
      fullPath: '/article/$category/$postTitle'
      preLoaderRoute: typeof ArticleCategoryPostTitleImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface ArticleLazyRouteChildren {
  ArticleWritingRoute: typeof ArticleWritingRoute
}

const ArticleLazyRouteChildren: ArticleLazyRouteChildren = {
  ArticleWritingRoute: ArticleWritingRoute,
}

const ArticleLazyRouteWithChildren = ArticleLazyRoute._addFileChildren(
  ArticleLazyRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/archive': typeof ArchiveLazyRoute
  '/article': typeof ArticleLazyRouteWithChildren
  '/archive/$projectTitle': typeof ArchiveProjectTitleRoute
  '/article/writing': typeof ArticleWritingRoute
  '/article/$category': typeof ArticleCategoryRoute
  '/article/$category/$postTitle': typeof ArticleCategoryPostTitleRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/archive': typeof ArchiveLazyRoute
  '/article': typeof ArticleLazyRouteWithChildren
  '/archive/$projectTitle': typeof ArchiveProjectTitleRoute
  '/article/writing': typeof ArticleWritingRoute
  '/article/$category': typeof ArticleCategoryRoute
  '/article/$category/$postTitle': typeof ArticleCategoryPostTitleRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/archive': typeof ArchiveLazyRoute
  '/article': typeof ArticleLazyRouteWithChildren
  '/archive_/$projectTitle': typeof ArchiveProjectTitleRoute
  '/article/writing': typeof ArticleWritingRoute
  '/article_/$category': typeof ArticleCategoryRoute
  '/article_/$category_/$postTitle': typeof ArticleCategoryPostTitleRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/archive'
    | '/article'
    | '/archive/$projectTitle'
    | '/article/writing'
    | '/article/$category'
    | '/article/$category/$postTitle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/archive'
    | '/article'
    | '/archive/$projectTitle'
    | '/article/writing'
    | '/article/$category'
    | '/article/$category/$postTitle'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/archive'
    | '/article'
    | '/archive_/$projectTitle'
    | '/article/writing'
    | '/article_/$category'
    | '/article_/$category_/$postTitle'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  ArchiveLazyRoute: typeof ArchiveLazyRoute
  ArticleLazyRoute: typeof ArticleLazyRouteWithChildren
  ArchiveProjectTitleRoute: typeof ArchiveProjectTitleRoute
  ArticleCategoryRoute: typeof ArticleCategoryRoute
  ArticleCategoryPostTitleRoute: typeof ArticleCategoryPostTitleRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  ArchiveLazyRoute: ArchiveLazyRoute,
  ArticleLazyRoute: ArticleLazyRouteWithChildren,
  ArchiveProjectTitleRoute: ArchiveProjectTitleRoute,
  ArticleCategoryRoute: ArticleCategoryRoute,
  ArticleCategoryPostTitleRoute: ArticleCategoryPostTitleRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/archive",
        "/article",
        "/archive_/$projectTitle",
        "/article_/$category",
        "/article_/$category_/$postTitle"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/archive": {
      "filePath": "archive.lazy.tsx"
    },
    "/article": {
      "filePath": "article.lazy.tsx",
      "children": [
        "/article/writing"
      ]
    },
    "/archive_/$projectTitle": {
      "filePath": "archive_.$projectTitle.tsx"
    },
    "/article/writing": {
      "filePath": "article.writing.tsx",
      "parent": "/article"
    },
    "/article_/$category": {
      "filePath": "article_.$category.tsx"
    },
    "/article_/$category_/$postTitle": {
      "filePath": "article_.$category_.$postTitle.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
